<script setup>
import{ref,onMounted}from'vue';import{api,json}from'../api';import{Plus,Pencil,Trash2,Search}from'lucide-vue-next';import Modal from'../components/Modal.vue';import Toast from'../components/Toast.vue'
const rows=ref([]),keyword=ref(''),show=ref(false),form=ref({}),toast=ref('');function msg(s){toast.value=s;setTimeout(()=>toast.value='',2200)}
async function load(){try{rows.value=await api(`/api/admin/user/page?keyword=${encodeURIComponent(keyword.value)}`)}catch(e){msg(e.message)}}
function edit(row={username:'',password:'',name:'',phone:''}){form.value={...row,password:''};show.value=true}
async function save(){try{await api('/api/admin/user',{method:form.value.id?'PUT':'POST',body:json(form.value)});show.value=false;msg('Saved');load()}catch(e){msg(e.message)}}
async function remove(r){if(!confirm(`Delete customer "${r.username}"?`))return;try{await api(`/api/admin/user/${r.id}`,{method:'DELETE'});msg('Deleted');load()}catch(e){msg(e.message)}}
onMounted(load)
</script>
<template><div class="page-head"><div><h1>Customers</h1><p>Manage customer accounts</p></div><button class="primary" @click="edit()"><Plus :size="18"/>Add Customer</button></div><div class="filters"><input v-model="keyword" placeholder="Username, name or phone" @keyup.enter="load"><button class="secondary" @click="load"><Search :size="16"/>Search</button></div><div class="table-wrap"><table><thead><tr><th>Username</th><th>Name</th><th>Phone</th><th>Joined</th><th class="actions">Actions</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><strong>{{r.username}}</strong></td><td>{{r.name}}</td><td>{{r.phone}}</td><td>{{r.createTime?.replace('T',' ')}}</td><td class="actions"><button title="Edit" @click="edit(r)"><Pencil/></button><button title="Delete" class="danger" @click="remove(r)"><Trash2/></button></td></tr></tbody></table></div><Modal v-if="show" :title="form.id?'Edit Customer':'Add Customer'" @close="show=false"><form class="form-grid" @submit.prevent="save"><label>Username<input v-model="form.username" :readonly="!!form.id" required/></label><label>Password<input v-model="form.password" type="password" :required="!form.id" :placeholder="form.id?'Leave blank to keep current':''"/></label><label>Name<input v-model="form.name" required/></label><label>Phone<input v-model="form.phone"/></label><footer><button type="button" class="secondary" @click="show=false">Cancel</button><button class="primary">Save</button></footer></form></Modal><Toast :message="toast"/></template>
