CREATE DATABASE IF NOT EXISTS sky_take_out DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sky_take_out;
CREATE TABLE IF NOT EXISTS employee (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(32) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL, name VARCHAR(32) NOT NULL, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS category (id BIGINT PRIMARY KEY AUTO_INCREMENT, type VARCHAR(20) NOT NULL, name VARCHAR(32) NOT NULL, sort INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS dish (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(64) NOT NULL, category_id BIGINT NOT NULL, price DECIMAL(10,2) NOT NULL, image VARCHAR(255), description VARCHAR(255), status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_dish_category FOREIGN KEY (category_id) REFERENCES category(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS setmeal (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(64) NOT NULL, category_id BIGINT NOT NULL, price DECIMAL(10,2) NOT NULL, image VARCHAR(255), description VARCHAR(255), status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_setmeal_category FOREIGN KEY (category_id) REFERENCES category(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS setmeal_dish (id BIGINT PRIMARY KEY AUTO_INCREMENT, setmeal_id BIGINT NOT NULL, dish_id BIGINT NOT NULL, copies INT NOT NULL DEFAULT 1, UNIQUE KEY uk_setmeal_dish (setmeal_id, dish_id), CONSTRAINT fk_sd_setmeal FOREIGN KEY (setmeal_id) REFERENCES setmeal(id) ON DELETE CASCADE, CONSTRAINT fk_sd_dish FOREIGN KEY (dish_id) REFERENCES dish(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `user` (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(64) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL, name VARCHAR(32) NOT NULL, avatar VARCHAR(255), phone VARCHAR(20), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS address_book (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, consignee VARCHAR(32) NOT NULL, sex VARCHAR(2), phone VARCHAR(20) NOT NULL, detail VARCHAR(255) NOT NULL, label VARCHAR(20), is_default TINYINT NOT NULL DEFAULT 0, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS shopping_cart (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, dish_id BIGINT, setmeal_id BIGINT, name VARCHAR(64) NOT NULL, image VARCHAR(255), amount DECIMAL(10,2) NOT NULL, number INT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_cart_user_dish (user_id, dish_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (id BIGINT PRIMARY KEY AUTO_INCREMENT, number VARCHAR(32) NOT NULL UNIQUE, user_id BIGINT NOT NULL, address_book_id BIGINT NOT NULL, status TINYINT NOT NULL DEFAULT 1, reminder TINYINT NOT NULL DEFAULT 0, user_deleted TINYINT NOT NULL DEFAULT 0, amount DECIMAL(10,2) NOT NULL, original_amount DECIMAL(10,2), discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0, coupon_code VARCHAR(32), remark VARCHAR(255), consignee VARCHAR(32) NOT NULL, phone VARCHAR(20) NOT NULL, address VARCHAR(255) NOT NULL, order_time DATETIME NOT NULL, pay_time DATETIME, delivery_time DATETIME, checkout_time DATETIME, cancel_time DATETIME, INDEX idx_orders_user (user_id), CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES `user`(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_detail (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL, dish_id BIGINT, setmeal_id BIGINT, name VARCHAR(64) NOT NULL, image VARCHAR(255), amount DECIMAL(10,2) NOT NULL, number INT NOT NULL, CONSTRAINT fk_detail_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS coupon (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(64) NOT NULL, discount_amount DECIMAL(10,2) NOT NULL, threshold_amount DECIMAL(10,2) NOT NULL DEFAULT 0, total_stock INT NOT NULL DEFAULT 0, remaining_stock INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_coupon (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, coupon_id BIGINT NOT NULL, status TINYINT NOT NULL DEFAULT 0, claimed_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, used_time DATETIME, order_id BIGINT, UNIQUE KEY uk_user_coupon (user_id,coupon_id), CONSTRAINT fk_uc_user FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE, CONSTRAINT fk_uc_coupon FOREIGN KEY (coupon_id) REFERENCES coupon(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rider (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(32) NOT NULL, phone VARCHAR(20) NOT NULL UNIQUE, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS delivery (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL UNIQUE, rider_id BIGINT, status TINYINT NOT NULL DEFAULT 0, assigned_time DATETIME, picked_time DATETIME, delivered_time DATETIME, CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_delivery_rider FOREIGN KEY (rider_id) REFERENCES rider(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS shop (id TINYINT PRIMARY KEY, status TINYINT NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO shop(id,status) VALUES (1,1);
INSERT IGNORE INTO rider(name,phone,status) VALUES ('Rider Wang','13800000001',1),('Rider Li','13800000002',1);
INSERT IGNORE INTO coupon(code,name,discount_amount,threshold_amount,total_stock,remaining_stock,status,start_time,end_time) VALUES ('NEW5','New customer ¥5 off',5,30,999,999,1,NOW(),DATE_ADD(NOW(),INTERVAL 365 DAY)),('SAVE10','¥10 off orders over ¥60',10,60,999,999,1,NOW(),DATE_ADD(NOW(),INTERVAL 365 DAY));
INSERT IGNORE INTO category(id,type,name,sort,status) VALUES (1,'1','Staples',2,1),(2,'1','Snacks',3,1),(3,'2','Set Meals',5,1),(4,'1','Mains',1,1),(5,'1','Drinks',4,1);
-- Starter menu. The ids match the photos in user-frontend/public/images/dishes (see dishImage in user-frontend/src/App.vue).
INSERT IGNORE INTO dish(id,name,category_id,price,description,status) VALUES
(3,'Kung Pao Chicken',4,28.00,'Diced chicken stir-fried with peanuts, chili and Sichuan pepper',1),
(26,'Sichuan Boiled Pork Slices',4,38.00,'Tender pork slices in a spicy chili broth',1),
(31,'Sweet and Sour Pork',4,32.00,'Crispy pork strips in a sweet and tangy sauce with sesame',1),
(32,'Mixed Grill Platter',4,58.00,'Grilled meat skewers with roasted vegetables and dips',1),
(33,'BBQ Pork Ribs',4,48.00,'Slow-cooked ribs in barbecue sauce, served with fries',1),
(35,'Grilled Beef Skewers',4,36.00,'Spiced beef skewers with fries and fresh vegetables',1),
(24,'Spicy Noodle Soup',1,22.00,'Wide noodles in chili broth with a braised meat topping',1),
(27,'Shrimp Fried Rice',1,24.00,'Wok-fried rice with shrimp, herbs and fresh lemon',1),
(29,'Garden Salad Bowl',2,22.00,'Avocado, cherry tomatoes, chickpeas and mixed greens',1),
(34,'Seaweed and Egg Soup',2,12.00,'Light soup with seaweed, egg ribbons and scallions',1),
(28,'Cola',5,5.00,'Chilled 330 ml can',1);
